AdobeDocs/commerce-webapi

src/data/navigation/sections/rest.js
I've added external links in the side nav to the redoc.ly docs. 
I've left the `/quick-reference/index.md` in place because making a top-level page `path` external causes the an error when viewing the page.
=> Adding external links in side nav

src/pages/get-started/api-security.md, src/pages/get-started/authentication/gs-authentication-token.md, src/pages/get-started/authentication/index.md, src/pages/get-started/gs-web-api-request.md, src/pages/get-started/index.md, src/pages/rest/b2b/negotiable-order-workflow.md, src/pages/rest/quick-reference/generate-local.md, src/pages/rest/tutorials/inventory/configure-environment.md, src/pages/rest/tutorials/inventory/create-sources.md, src/pages/rest/tutorials/inventory/create-stock.md, src/pages/rest/tutorials/inventory/index.md, src/pages/rest/use-rest/bulk-endpoints.md
This pull request (PR) replaces links to `https://devdocs.magento.com` topics that have already been migrated to the Adobe Devsite (`https://developer.adobe.com`).
- See changed files
=> Replace obsolete devdocs links

src/data/navigation/sections/rest.js, src/pages/rest/attributes.md
This pull request (PR) migrates the [Attributes](https://devdocs.magento.com/codelinks/attributes.html) topic from the `devdocs.magento.com` site to the Adobe DevSite.
The tables are overlapping with the "on page" nav on the right. Hoever, that's a known issue/bug with the aio-theme. There's a ticket in the Devsite team's backlog to fix it.
- **Staging**: https://adobedocs.github.io/commerce-webapi/rest/attributes/
- COMDOX-351
=> COMDOX-351: Migrate API endpoint attributes file from magento/devdocs

src/pages/rest/quick-reference/index.md
Changing link in Redoc from https://good-stingray-87.redoc.ly to
https://adobe-commerce.redoc.ly
See also: https://github.com/magento-commerce/devdocs/pull/3204
=> Redoc link name change

src/pages/index.md, src/pages/rest/index.md, src/pages/rest/tutorials/index.md, src/pages/rest/tutorials/inventory/index.md, src/pages/rest/tutorials/orders/index.md, src/pages/rest/tutorials/orders/order-issue-refund.md
Replaced links to magento.redoc.ly.
#50 
The old link no longer works because we cancelled our Pro Redocly subscription when we migrated to the Enterpise plan under the Adobe Developers org.
We're not able to create a redirect.
GitHub Actions PR validation
N/A
=> Replace link to old redocly site

src/pages/_includes/graphql/cart-object-24.md
This PR fixes broken links in the [Cart object](https://developer.adobe.com/commerce/webapi/graphql/schema/cart/mutations/set-shipping-address/#cart-object) table in the GraphQL docs. It also fixes some inconsistent inline code formatting.
You must use absolute links instead of relative links in includes files.
This PR only addresses links in one include file to address an issue reported by a customer. Someone will need to open a separate PR to address relative links in all other include files in this repo.
**Staging:** https://adobedocs.github.io/commerce-webapi/graphql/schema/cart/mutations/set-shipping-address/#cart-object
COMDOX-429
=> COMDOX-429: Convert relative links to absolute (setShippingAddressesOnCart mutation)

src/pages/_includes/graphql/cart-object-24.md
This PR reverts formatting changes made in #67, which are necessary for indicating an array. 
- COMDOX-429
- #67
=> COMDOX-429: Revert formatting for arrays (setShippingAddressesOnCart mutation)

src/pages/graphql/schema/products/queries/route.md
I think its better to use singular 'route' instead of 'routes'.
"The `routes` query returns..." such phrases look a little disorienting, when 'routes' are specified in plural.
-  https://developer.adobe.com/commerce/webapi/graphql/schema/products/queries/route/
=> Change 'routes' to 'route'

src/pages/graphql/schema/products/interfaces/routable.md
New concrete type `RoutableUrl` was added that implements `RoutableInterface` and inherits the following fields with no additional fields.
```
relative_url
redirect_code
type
```
Document to be updated:
https://developer.adobe.com/commerce/webapi/graphql/schema/products/interfaces/routable/
[ACP2E-1494](https://jira.corp.adobe.com/browse/ACP2E-1494): Url Rewrite to external URL does not work on GraphQL
=> ACP2E-1598: [Documentation] Update GraphQL documentation to reflect changes introduced in ACP2E-1494

package.json, src/pages/graphql/reference.md, static/graphql-api/index.html, yarn.lock
Goal of this PR is to fix rendering of the page generated by Specatql:
- Updates the theme and other dependencies
- Replaces absolute link for framing in the topic to a relative link because it is supported by the update version of the theme
Preview: https://adobedocs.github.io/commerce-webapi/graphql/reference/
On the landing page the styling has changed. Not sure if it's expected.
Compare:
- Production: https://developer.adobe.com/commerce/webapi/
- Current preview: https://adobedocs.github.io/commerce-webapi/
=> Fix rendering for the GraphQL API reference

src/pages/_includes/graphql/create-customer.md
The description was not correct for the field is_subscribed in [Input Attributes](https://developer.adobe.com/commerce/webapi/graphql/schema/customer/mutations/create/#input-attributes) :  
Previous value: 'The customer's new password'
Proposed value: 'Indicates whether the customer is subscribed to the company's newsletter'
Same value as in the [Output Attributes](https://developer.adobe.com/commerce/webapi/graphql/schema/customer/mutations/create/#output-attributes). 
N/A
Incorrect information
N/A
=> Fix wrong description on is_subscribed

src/pages/get-started/api-security.md
Reading the documentation, and this page in particular, i've noticed a typo in the magento command "cache:clean"
it was reported as cache:clear instead.
i've found no issue, sorry, but willing to help, it's just a typo fixing.
the command was wrong.
trying the command in a project.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have read the **CONTRIBUTING** document.
=> Fixed typo cache:clear to cache:clean in page

src/pages/graphql/schema/cart/mutations/add-products.md
This pull request (PR) fixes naming of "entered_options"
https://developer.adobe.com/commerce/webapi/graphql/schema/cart/mutations/add-products/
https://github.com/magento-commerce/magento2ce/blob/4c325de7a8a3182d3fde9ee2040df1279c67431f/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L61
=> Fix naming of entered_options

src/pages/rest/modules/import/index.md
This pull request (PR) fix incorrect `validationStrategy` parameter allowed value. The correct value for `validationStrategy` parameter should be `validation-stop-on-errors` or `validation-skip-errors`
- https://developer.adobe.com/commerce/webapi/rest/modules/import/
=> Fix incorrect `validationStrategy` parameter

src/data/navigation/sections/graphql.js, src/pages/graphql/schema/products/queries/route.md
This pull request (PR) fixes incorrect references to the `route` query.
- ...
- ...
=> Change routes to route

src/pages/graphql/develop/identity-class.md
This pull request (PR) formats GraphQL categoryList cache annotation example and removes trailing closing curly brace where there is no respective opening curly brace
- https://developer.adobe.com/commerce/webapi/graphql/develop/identity-class/
- Much nicer looking [here](https://github.com/magento-commerce/magento2ce/blob/137bd3740bc3cbc1e5bb4c5c15794e1d19cdce29/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L17) than the current formatting in the doc
=> Format categoryList GQL cache annotation example

src/pages/_includes/graphql/customer-address-input-24.md, src/pages/_includes/graphql/customer-address-output-24.md, src/pages/graphql/schema/customer/mutations/create-address.md, src/pages/graphql/schema/customer/mutations/update-address.md
This pull request (PR) is to update documentation:
- taking into account deprecated `custom_attributes` field for Customer address.
src/pages/_includes/graphql/customer-address-input-24.md
src/pages/_includes/graphql/customer-address-output-24.md
src/pages/graphql/schema/customer/mutations/create-address.md
src/pages/graphql/schema/customer/mutations/update-address.md
=> Update CustomerAddress.custom_attributes deprecation message and usage

src/pages/_includes/graphql/customer-address-output-24.md, src/pages/_includes/graphql/customer-output-24.md, src/pages/graphql/schema/customer/queries/customer.md
This pull request (PR) is to add uids filters to entity queries custom_attriubtes fields.
src/pages/_includes/graphql/customer-address-output-24.md
src/pages/_includes/graphql/customer-output-24.md
src/pages/graphql/schema/customer/queries/customer.md
https://github.com/magento-lynx/magento2ce/pull/117
=> LYNX-162: Add uids filters to entity queries custom_attriubtes fields

src/data/navigation/sections/graphql.js
This pull request (PR) removes a duplicated section of the left navigation of the GraphQL guide. Most likely, this duplication came from a merge non-conflict.
- ...
- ...
=> Remove duplicate section from left nav

src/pages/graphql/schema/cart/queries/cart.md
Added shipping discount breakdown for the GraphQL cart response. Introduced new Discount property "applied_to" to differentiate between discounts applied to a cart item or a shipping
graphql/schema/cart/queries/cart.md
https://github.com/magento-l3/magento2ce/pull/1150
https://github.com/magento-commerce/magento2ce/pull/8381
=> Update doc according to the changes introduced in ACP2E-2044

src/pages/_includes/graphql/customer-address-output-24.md, src/pages/graphql/schema/customer/mutations/create-address.md, src/pages/graphql/schema/customer/mutations/update-address.md, src/pages/graphql/schema/customer/queries/customer.md
This pull request (PR) replaces duplicated `CustomerAddress` object in the `customer` query with an include file. The other changes in this PR ensure all queries/mutations that return this object display this information in a consistent manner.
Sergio Vera alerted me to these discrepancies.
- https://developer.adobe.com/commerce/webapi/graphql/schema/customer/queries/customer/
- ...
=> Use include file in customer query

src/pages/graphql/schema/store/index.md, src/pages/graphql/schema/store/mutations/contact-us.md, src/pages/graphql/schema/store/mutations/index.md, src/pages/graphql/schema/store/queries/available-stores.md, src/pages/graphql/schema/store/queries/cms-blocks.md, src/pages/graphql/schema/store/queries/cms-page.md, src/pages/graphql/schema/store/queries/countries.md, src/pages/graphql/schema/store/queries/country.md, src/pages/graphql/schema/store/queries/currency.md, src/pages/graphql/schema/store/queries/dynamic-blocks.md, src/pages/graphql/schema/store/queries/index.md, src/pages/graphql/schema/store/queries/store-config.md
This pull request (PR) removes the manually maintained reference information from the topics in the `pages/graphql/schema/store`  directory.
The `reCaptchaV3Config` query and `contactUs` mutation are not included in this PR because I can't link to them in the 2.4.6 SpectaQLdocs. They will be addressed in COMDOX-727
- ...
- ...
=> GraphQL: Remove reference info from Store entities

src/data/navigation/sections/graphql.js, src/pages/graphql/schema/wishlist/index.md, src/pages/graphql/schema/wishlist/interfaces/index.md, src/pages/graphql/schema/wishlist/interfaces/wishlist.md, src/pages/graphql/schema/wishlist/mutations/add-items-to-cart.md, src/pages/graphql/schema/wishlist/mutations/add-products.md, src/pages/graphql/schema/wishlist/mutations/copy-products.md, src/pages/graphql/schema/wishlist/mutations/create.md, src/pages/graphql/schema/wishlist/mutations/delete.md, src/pages/graphql/schema/wishlist/mutations/index.md, src/pages/graphql/schema/wishlist/mutations/move-products.md, src/pages/graphql/schema/wishlist/mutations/remove-products.md, src/pages/graphql/schema/wishlist/mutations/update-products.md, src/pages/graphql/schema/wishlist/mutations/update.md, src/pages/graphql/schema/wishlist/queries/index.md, src/pages/graphql/schema/wishlist/queries/wishlist.md
This pull request (PR) removes the manually maintained reference information from the topics in the pages/graphql/schema/wishlist directory.
Staging build: https://developer-stage.adobe.com/commerce/webapi/graphql/schema/wishlist/
- ...
- ...
=> GraphQL: Remove reference info from Wishlist entities

src/pages/graphql/schema/gift-registry/index.md, src/pages/graphql/schema/gift-registry/mutations/add-registrants.md, src/pages/graphql/schema/gift-registry/mutations/create.md, src/pages/graphql/schema/gift-registry/mutations/index.md, src/pages/graphql/schema/gift-registry/mutations/move-cart-items.md, src/pages/graphql/schema/gift-registry/mutations/remove-items.md, src/pages/graphql/schema/gift-registry/mutations/remove-registrants.md, src/pages/graphql/schema/gift-registry/mutations/remove.md, src/pages/graphql/schema/gift-registry/mutations/share.md, src/pages/graphql/schema/gift-registry/mutations/update-items.md, src/pages/graphql/schema/gift-registry/mutations/update-registrants.md, src/pages/graphql/schema/gift-registry/mutations/update.md, src/pages/graphql/schema/gift-registry/queries/email-search.md, src/pages/graphql/schema/gift-registry/queries/gift-registry.md, src/pages/graphql/schema/gift-registry/queries/id-search.md, src/pages/graphql/schema/gift-registry/queries/index.md, src/pages/graphql/schema/gift-registry/queries/type-search.md, src/pages/graphql/schema/gift-registry/queries/types.md
This pull request (PR) removes the manually maintained reference information from the topics in the `pages/graphql/schema/gift-registry` directory.
Staging build: https://developer-stage.adobe.com/commerce/webapi/graphql/schema/gift-registry/
- ...
- ...
=> GraphQL: Remove reference info from Gift Registry section

src/pages/graphql/schema/orders/index.md, src/pages/graphql/schema/orders/interfaces/credit-memo-item.md, src/pages/graphql/schema/orders/interfaces/index.md, src/pages/graphql/schema/orders/interfaces/invoice-item.md, src/pages/graphql/schema/orders/interfaces/order-item.md, src/pages/graphql/schema/orders/interfaces/shipment-item.md, src/pages/graphql/schema/orders/mutations/add-return-comment.md, src/pages/graphql/schema/orders/mutations/add-return-tracking.md, src/pages/graphql/schema/orders/mutations/index.md, src/pages/graphql/schema/orders/mutations/remove-return-tracking.md, src/pages/graphql/schema/orders/mutations/reorder-items.md, src/pages/graphql/schema/orders/mutations/request-return.md
This pull request (PR) removes the manually maintained reference information from the topics in the pages/graphql/schema/orders directory.
Staging build: https://developer-stage.adobe.com/commerce/webapi/graphql/schema/orders/
- ...
- ...
=> GraphQL: Remove reference info from Orders section

src/_includes/graphql/company-team.md, src/pages/graphql/schema/b2b/company/queries/company.md
This pull request (PR) is to add a missing parameter to GraphQL response
- https://developer.adobe.com/commerce/webapi/graphql/schema/b2b/company/queries/company/
- https://jira.corp.adobe.com/browse/ACP2E-2081
- https://jira.corp.adobe.com/browse/ACP2E-1968
=> ACP2E-2081: [Documentation] CompanyTeam attributes list needs to be updated

package.json
This pull request (PR) removes a duplicate `remark` config that I overlooked in #201. The config was moved [here](https://github.com/AdobeDocs/commerce-webapi/blob/main/.remarkrc.mjs#L7).
=> COMDOX-345: Remove duplicate remark config

src/openapi/admin-schema-2.4.6.yaml, src/openapi/customer-schema-2.4.6.yaml, src/openapi/guest-schema-2.4.6.yaml
This PR builds on the work done in PR #200 and adds links to the `2.4.6` schemas.
Example preview: https://preview.redoc.ly/warm-baboon-65/jh_redocly_intro_2/
This affects the Redocly site embedded on the [REST page](https://developer.adobe.com/commerce/webapi/rest/quick-reference/).
=> COMDOX-570: Adding intro to `2.4.6` schemas

src/_includes/graphql/cache/queries-247beta.md
This pull request (PR) adds the list of cacheable queries. The corresponding code updates were discovered while reviewing the 2.4.7 beta2 release notes.
- ...
- ...
=> Add EAV queries to list of cacheable queries

src/pages/graphql/schema/customer/queries/is-email-available.md
This pull request (PR) add a note to the isEmailAvailable query description that it's default behavior has been changed.
- https://developer.adobe.com/commerce/webapi/graphql/schema/customer/queries/is-email-available/
- ...
=> ACP2E-2419: Document the updated behavior of isEmailAvailable endpoint in 2.4.7-b1

.github/workflows/index.yml
This pull request (PR) fixes a potential indexing workflow [failure](https://github.com/AdobeDocs/commerce-extensibility/actions/runs/6724894582/job/18278143476). Downgrading yarn to v3 in the workflow like in other workflows.
yarn v4 doesn't support node v16.
https://github.com/commerce-docs/commerce-extensibility/actions/runs/6725364432/job/18279583045
=> Fix indexing workflow

src/pages/graphql/schema/b2b/company/index.md, src/pages/graphql/schema/b2b/company/mutations/create-role.md, src/pages/graphql/schema/b2b/company/mutations/create-team.md, src/pages/graphql/schema/b2b/company/mutations/create-user.md, src/pages/graphql/schema/b2b/company/mutations/create.md, src/pages/graphql/schema/b2b/company/mutations/delete-role.md, src/pages/graphql/schema/b2b/company/mutations/delete-team.md, src/pages/graphql/schema/b2b/company/mutations/delete-user.md, src/pages/graphql/schema/b2b/company/mutations/index.md, src/pages/graphql/schema/b2b/company/mutations/update-role.md, src/pages/graphql/schema/b2b/company/mutations/update-structure.md, src/pages/graphql/schema/b2b/company/mutations/update-team.md, src/pages/graphql/schema/b2b/company/mutations/update-user.md, src/pages/graphql/schema/b2b/company/mutations/update.md, src/pages/graphql/schema/b2b/company/queries/company.md, src/pages/graphql/schema/b2b/company/queries/index.md, src/pages/graphql/schema/b2b/company/queries/is-company-admin-email-available.md, src/pages/graphql/schema/b2b/company/queries/is-company-email-available.md, src/pages/graphql/schema/b2b/company/queries/is-company-role-name-available.md, src/pages/graphql/schema/b2b/company/queries/is-company-user-email-available.md, src/pages/graphql/schema/b2b/company/unions/index.md, src/pages/graphql/schema/b2b/company/unions/structure-entity.md
This pull request (PR) removes reference information from the B2B Company queries/mutations/union and adds links to SpectaQL. Also added content to index pages and added missing token information.
- ...
- ...
=> GraphQL: Remove reference info from Company section

src/pages/graphql/schema/b2b/purchase-order-rule/interfaces/index.md, src/pages/graphql/schema/b2b/purchase-order-rule/mutations/create.md, src/pages/graphql/schema/b2b/purchase-order-rule/mutations/delete.md, src/pages/graphql/schema/b2b/purchase-order-rule/mutations/index.md, src/pages/graphql/schema/b2b/purchase-order-rule/mutations/update.md, src/pages/graphql/schema/b2b/purchase-order-rule/mutations/validate.md, src/pages/graphql/schema/b2b/purchase-order/mutations/add-comment.md, src/pages/graphql/schema/b2b/purchase-order/mutations/add-items-to-cart.md, src/pages/graphql/schema/b2b/purchase-order/mutations/approve.md, src/pages/graphql/schema/b2b/purchase-order/mutations/cancel.md, src/pages/graphql/schema/b2b/purchase-order/mutations/index.md, src/pages/graphql/schema/b2b/purchase-order/mutations/place-order.md, src/pages/graphql/schema/b2b/purchase-order/mutations/place-purchase-order.md, src/pages/graphql/schema/b2b/purchase-order/mutations/reject.md
This pull request (PR) removes reference information from the B2B purchase order/purchase order rules queries/mutations/interface and adds links to SpectaQL. Also added content to index pages.
- ...
- ...
=> GraphQL: Remove reference info from purchase order/po rules sections

src/data/navigation/sections/graphql.js, src/pages/graphql/schema/b2b/requisition-list/index.md, src/pages/graphql/schema/b2b/requisition-list/interfaces/index.md, src/pages/graphql/schema/b2b/requisition-list/interfaces/item.md, src/pages/graphql/schema/b2b/requisition-list/mutations/add-items-to-cart.md, src/pages/graphql/schema/b2b/requisition-list/mutations/add-products.md, src/pages/graphql/schema/b2b/requisition-list/mutations/clear-customer-cart.md, src/pages/graphql/schema/b2b/requisition-list/mutations/copy-items.md, src/pages/graphql/schema/b2b/requisition-list/mutations/create.md, src/pages/graphql/schema/b2b/requisition-list/mutations/delete-items.md, src/pages/graphql/schema/b2b/requisition-list/mutations/delete.md, src/pages/graphql/schema/b2b/requisition-list/mutations/index.md, src/pages/graphql/schema/b2b/requisition-list/mutations/move-items.md, src/pages/graphql/schema/b2b/requisition-list/mutations/update-items.md, src/pages/graphql/schema/b2b/requisition-list/mutations/update.md
This pull request (PR) removes reference info from the requisition list section of the GraphQL schema docs.
- ...
- ...
=> GraphQL: Remove reference info from requisition list section

src/pages/graphql/schema/attributes/index.md, src/pages/graphql/schema/attributes/queries/attributes-form.md, src/pages/graphql/schema/attributes/queries/attributes-list.md, src/pages/graphql/schema/attributes/queries/attributes-metadata.md, src/pages/graphql/schema/attributes/queries/custom-attribute-metadata-v2.md, src/pages/graphql/schema/attributes/queries/custom-attribute-metadata.md, src/pages/graphql/schema/attributes/queries/index.md
This pull request (PR) removes the manually maintained reference information from the topics in the pages/graphql/schema/attributes directory.
- ...
- ...
=> GraphQL: Remove reference info from Attributes section

src/data/navigation/sections/graphql.js
This pull request (PR) adds version clarity to the TOC for GraphQL API reference pages.
According to PM, the current nav is confusing customers. They "think all of our APIs are in beta..."
PM agreed that this was an acceptable solution for now, but we should re-examine how we do this for future betas.
=> Add core versions to graphql API ref TOC

src/pages/rest/tutorials/bulk-configurable-product/create-configurable-simple-products.md
This pull request (PR) fixes bad formatting that causes the InlineAlert to render without text. 
- https://developer.adobe.com/commerce/webapi/rest/tutorials/bulk-configurable-product/create-configurable-simple-products/
=> Fix note formatting

src/pages/graphql/schema/b2b/company/mutations/create.md
Remove note that Authentification header is required.  Cause you can create company without defining it.
Remove confusion for developers. Cause its not true that you need an account to be able to create a company
https://developer.adobe.com/commerce/webapi/graphql/schema/b2b/company/mutations/create/
=> Remove note that Authentification header is required. 

src/pages/graphql/payment-methods/klarna.md
This pull request (PR) fixes broken links to the Klarna developer documentation.
- ...
- ...
=> Update links to Klarna docs

src/data/navigation/sections/graphql.js, src/pages/graphql/schema/cart/mutations/create-guest-cart.md
This pull request (PR) updates the [CreateGuestCart](https://developer.adobe.com/commerce/webapi/graphql/schema/cart/mutations/create-guest-cart/) page to include a direct link to the [SpectaQL listing](https://developer.adobe.com/commerce/webapi/graphql-api/beta/index.html#mutation-createGuestCart) and removes information that the link makes redundant. As requested by @keharper.
=> update link in CreateGuestCart

src/pages/graphql/schema/checkout/index.md
This pull request (PR) fixes a small typo in a URL.
- https://developer.adobe.com/commerce/webapi/graphql/schema/checkout/
=> Fixed typo in a URL

src/pages/graphql/schema/store/queries/store-config.md
This pull request (PR) is to add into the documentation how to query the configuration for access token expiration. It is related to this ticket: [LYNX-375](https://jira.corp.adobe.com/browse/LYNX-375)
- https://developer.adobe.com/commerce/webapi/graphql/schema/store/queries/store-config/
- ...
=> LYNX-375: Add doc of the token expiration config

src/pages/graphql/schema/cart/interfaces/index.md, src/pages/graphql/schema/cart/mutations/add-bundle-products.md, src/pages/graphql/schema/cart/mutations/add-configurable-products.md, src/pages/graphql/schema/cart/mutations/add-downloadable-products.md, src/pages/graphql/schema/cart/mutations/add-products.md, src/pages/graphql/schema/cart/mutations/add-simple-products.md, src/pages/graphql/schema/cart/mutations/add-virtual-products.md, src/pages/graphql/schema/cart/mutations/apply-coupon.md, src/pages/graphql/schema/cart/mutations/apply-reward-points.md, src/pages/graphql/schema/cart/mutations/assign-customer-to-guest-cart.md, src/pages/graphql/schema/cart/mutations/merge.md, src/pages/graphql/schema/cart/mutations/remove-coupon.md, src/pages/graphql/schema/cart/mutations/remove-item.md, src/pages/graphql/schema/cart/mutations/set-gift-options.md, src/pages/graphql/schema/cart/mutations/update-items.md, src/pages/graphql/schema/cart/queries/cart.md, src/pages/graphql/schema/orders/mutations/reorder-items.md
This pull request (PR) replaces all examples making use of the deprecated `cart.items` by `cart.itemsV2`, which adds pagination capabilities.
This field is already present in 2.4.7-beta3
=> LYNX-329: Updated examples returning cart items field to use itemsV2

src/pages/graphql/schema/attributes/queries/attributes-form.md
This pull request (PR) is to change the documentation to reflect that now the **attributes options** for country_id and region_id codes are not included in the query result but the **attributes** country_id and region_id are included. 
Also I removed a duplicated word.
Jira Ticket: [LYNX-332](https://jira.corp.adobe.com/browse/LYNX-332)
- https://developer.adobe.com/commerce/webapi/graphql/schema/attributes/queries/attributes-form/
- ...
=> LYNX-332: change attributeForm note

src/pages/graphql/schema/cart/mutations/estimate-shipping-methods.md, src/pages/graphql/schema/cart/mutations/index.md
This PR provides documentation for `estimateShippingMethods` mutation.
See https://jira.corp.adobe.com/browse/LYNX-385 for details.
Implementation ticket for the mutation: https://jira.corp.adobe.com/browse/LYNX-305
- src/pages/graphql/schema/cart/mutations/estimate-shipping-methods.md
- src/pages/graphql/schema/cart/mutations/index.md
=> LYNX-385: documentation for estimateShippingMethods mutation

src/data/navigation/sections/graphql.js, src/data/navigation/sections/rest.js, src/pages/graphql/schema/cart/mutations/clear-cart.md, src/pages/graphql/schema/cart/mutations/create-guest-cart.md, src/pages/graphql/schema/cart/mutations/estimate-shipping-methods.md, src/pages/graphql/schema/cart/mutations/estimate-totals.md, src/pages/graphql/schema/customer/mutations/confirm-email.md
This pull request (PR) adds links to the 2.4.7 SpectaQL docs. I also added missing left navigation
- ...
- ...
=> Add links to SpectaQL docs

src/pages/get-started/authentication/oauth-errors.md
If you try to use HMAC-SHA1 you get the following 400 bad request response:
`{
"message": "Signature method %1 is not supported",
"parameters": [
"HMAC-SHA1"
]
}`
- https://developer.adobe.com/commerce/webapi/get-started/authentication/oauth-errors/
- ...
=> INTERNAL - Update oauth signature method supported

src/pages/rest/tutorials/inventory/create-shipment.md
This pull request is to mention that POST "/order/{orderId}/ship" REST API call does not validate total shipped items quantity.
Please also mention that to validate total shipped quantity for each item in the order POST "/order/{orderId}/ship" REST API call must be used.
https://developer.adobe.com/commerce/webapi/rest/tutorials/inventory/create-shipment/
=> Please mention that POST "ship" REST API call does not validate total shipped items quantity.

src/pages/graphql/index.md, src/pages/graphql/schema/cart/queries/cart.md, src/pages/graphql/schema/store/queries/store-config.md
This pull request (PR) adds links to the GraphQL API playground at https://experienceleague.adobe.com/developer/commerce/storefront/playgrounds/commerce-services/
I'm not including a link to `wishlist_v2` because the query is currently broken. I'll follow up when it's fixed.
- ...
- ...
=> Add links to API playground

src/pages/rest/modules/import/index.md
This pull request (PR) adds the `edition: ee` tag to the Import Data topic
https://developer.adobe.com/commerce/webapi/rest/modules/import/#import-csv-api
- ...
- ...
=> Add Commerce-only tag to import topic

src/pages/rest/tutorials/bulk-configurable-product/create-configurable-simple-products.md
This PR fixes an error in a `CodeBlock` that prevented the tabs from being usable.
=> fixing code block

.github/CODE_OF_CONDUCT.md, .github/linters/.textlintrc, README.md, src/pages/graphql/schema/checkout/mutations/create-payment-order.md, src/pages/graphql/schema/checkout/queries/get-payment-config.md, src/pages/graphql/schema/products/queries/url-resolver.md, src/pages/graphql/schema/store/queries/country.md, src/pages/graphql/tutorials/checkout/create-cart.md, src/pages/graphql/usage/security-configuration.md, src/pages/rest/b2b/company-structures.md, src/pages/rest/use-rest/anonymous-api-security.md
This pull request (PR) fixes issues found by the natural language linter. The errors that remain will be addressed by new rules that allow instances of `README` and prevent checks on words enclosed in bold.
- ...
- ...
=> Fix natural language linting errors

src/pages/get-started/api-security.md, src/pages/graphql/schema/cart/mutations/set-payment-place-order.md, src/pages/graphql/schema/checkout/mutations/create-braintree-client-token.md, src/pages/graphql/schema/store/queries/dynamic-blocks.md, src/pages/graphql/tutorials/checkout/apply-coupon.md, src/pages/graphql/tutorials/checkout/index.md, src/pages/graphql/usage/caching.md, src/pages/graphql/usage/staging-queries.md, src/pages/rest/b2b/index.md, src/pages/rest/inventory/manage-source-items.md, src/pages/rest/modules/import/index.md, src/pages/rest/tutorials/index.md, src/pages/rest/tutorials/orders/index.md
This pull request (PR) replace links to decommissioned resources with up-to-date links.
- https://developer.adobe.com/commerce/webapi//get-started/api-security/
- https://developer.adobe.com/commerce/webapi//graphql/schema/cart/mutations/set-payment-place-order/
- https://developer.adobe.com/commerce/webapi//graphql/schema/checkout/mutations/create-braintree-client-token/
- https://developer.adobe.com/commerce/webapi//graphql/schema/store/queries/dynamic-blocks/
- https://developer.adobe.com/commerce/webapi//graphql/tutorials/checkout/apply-coupon/
- https://developer.adobe.com/commerce/webapi//graphql/tutorials/checkout/
- https://developer.adobe.com/commerce/webapi//graphql/usage/caching/
- https://developer.adobe.com/commerce/webapi//graphql/usage/staging-queries/
- …
=> Replace links to decommissioned resources

src/pages/graphql/schema/orders/mutations/confirm-return.md, src/pages/graphql/schema/orders/mutations/request-guest-return.md
This pull request (PR) add two new entries into order/mutations, both related with the newly introduced feature of allowing returns (RMA) for guests
* `requestGuestReturn`
* `confirmReturn`
=> LYNX-572: Added entries for new RMA mutations

src/data/navigation/sections/graphql.js
This pull request (PR) adds navigation as a follow-up to #385 
- ...
- ...
=> Add navigation for returns mutations

src/pages/graphql/tutorials/checkout/add-product-to-cart.md
This PR updates [this tutorial page](https://developer.adobe.com/commerce/webapi/graphql/tutorials/checkout/add-product-to-cart/) to include `itemsV2`. ~It also changes the example product to one found in the current Venia catalog.~
=> Adding ItemsV2 to tutorial

src/pages/graphql/payment-services-extension/queries/get-payment-config.md
This pull request (PR) updates the `getPaymentConfig` query with the correct `three_ds_mode` attribute. Now, the `three_ds` attribute is deprecated since implementation of PS extension version 2.10.0.
- ...
- ...
=> Updates the `getPaymentConfig` query with the correct `three_ds_mode` attribute

spectaql/comdox-theme/views/partials/graphql/_query-or-mutation-or-subscription.hbs, spectaql/comdox-theme/views/partials/graphql/type.hbs, spectaql/config.yml
This pull request (PR) adds 'Jump to Top' hyperlink to GraphQL API reference at the end of each doc row for instant navigation to the top of the page which can be annoying for long pages via scrolling.
- https://developer.adobe.com/commerce/webapi/graphql/reference/
https://commerce-docs.github.io/commerce-webapi/graphql/reference/
=> Add 'Jump to Top' to GraphQL API reference

src/data/navigation/sections/graphql.js
#396 added a link in a paragraph to https://developer.adobe.com/commerce/webapi/graphql/reference/ and removed the TOC link to avoid duplicating the nav, but after looking at it today, I think the average user might not read that far and just assume the link is missing. 
This PR adds a direct link (opens in a new window) to the `2.4.7` GraphQL reference to the TOC to make it more obvious.
=> add external link to toc

.github/workflows/test-pull-request.yml
This pull request (PR) converts the test-pull-request workflow to a reusable workflow implemented in AdobeDocs/commerce-php/pull/351.
This will improve maintenance by reducing code duplication.
REQUIRED ACTIONS:
=> Convert test-pull-request workflow to reusable

spectaql/schema.json
This pull request (PR) manually removes queries that were deleted (not deprecated) from the codebase. Related to #421 
- ...
- ...
=> Remove deleted queries from schema

src/pages/graphql/payment-methods/hosted-pro.md, src/pages/graphql/payment-methods/klarna.md, src/pages/graphql/payment-methods/payflow-express.md, src/pages/graphql/payment-methods/payflow-link.md, src/pages/graphql/payment-methods/payflow-pro.md, src/pages/graphql/schema/cart/mutations/add-downloadable-products.md, src/pages/graphql/schema/cart/mutations/clear-cart.md, src/pages/graphql/schema/checkout/mutations/create-klarna-payments-session.md, src/pages/graphql/schema/checkout/mutations/create-payflow-pro-token.md, src/pages/graphql/schema/checkout/mutations/create-paypal-express-token.md, src/pages/graphql/schema/checkout/mutations/handle-payflow-pro-response.md, src/pages/graphql/schema/checkout/queries/get-hosted-pro-url.md, src/pages/graphql/schema/checkout/queries/get-payflow-link-token.md, src/pages/graphql/schema/customer/mutations/send-email-to-friend.md, src/pages/graphql/schema/customer/mutations/subscribe-email-to-newsletter.md, src/pages/graphql/schema/customer/queries/downloadable-products.md, src/pages/graphql/schema/products/mutations/create-review.md, src/pages/graphql/schema/products/queries/product-review-ratings-metadata.md, src/pages/graphql/schema/products/queries/products.md, src/pages/graphql/schema/products/queries/route.md, src/pages/graphql/schema/products/queries/url-resolver.md, src/pages/graphql/schema/store/mutations/contact-us.md, src/pages/graphql/schema/store/queries/cms-blocks.md, src/pages/graphql/schema/store/queries/cms-page.md, src/pages/graphql/schema/store/queries/dynamic-blocks.md, src/pages/graphql/usage/staging-queries.md
This pull request (PR) adds the PaaS only badge to multiple queries and mutations. These entities were excluded from the ACCS schema by disabling the corresponding *GraphQL module in the repo's `etc/config.php` file.
- ...
- ...
=> More PaaS-only queries and mutations

src/pages/graphql/schema/store/mutations/contact-us.md
This pull request (PR) removes the PaaS badge from the `contactUs` query. It was added to ACCS per CCSAAS-2146.
- ...
- ...
=> Remove PaaS badge from contactUs query

src/pages/get-started/api-security.md, src/pages/get-started/authentication/gs-authentication-oauth.md, src/pages/get-started/authentication/gs-authentication-session.md, src/pages/get-started/authentication/gs-authentication-token.md, src/pages/get-started/authentication/index.md, src/pages/get-started/create-integration.md, src/pages/get-started/gs-curl.md, src/pages/get-started/gs-web-api-request.md, src/pages/get-started/rate-limiting.md, src/pages/get-started/soap-web-api-calls.md, src/pages/get-started/web-api-functional-testing.md
This pull request (PR) marks blocks of information in the Getting Started Guide as PaaS-only.
- ...
- ...
=> Mark topics as PaaS only in Getting Started

src/pages/graphql/schema/customer/mutations/subscribe-email-to-newsletter.md
This pull request (PR) removes the PaaS only badge from the `subscribeEmailToNewsletter` mutation, per CSSAAS-2424
- ...
- ...
=> Re-enable subscribeEmailToNewsletter mutation for SaaS

src/_includes/graphql/catalog-service/categories.md, src/_includes/graphql/catalog-service/headers.md, src/_includes/graphql/catalog-service/product-view.md, src/_includes/graphql/customer-group-code.md, src/_includes/graphql/endpoints.md, src/_includes/graphql/live-search-headers.md, src/data/navigation/sections/graphql.js, src/pages/graphql/index.md, src/pages/graphql/schema/catalog-service/index.md, src/pages/graphql/schema/catalog-service/queries/categories.md, src/pages/graphql/schema/catalog-service/queries/index.md, src/pages/graphql/schema/catalog-service/queries/product-variants.md, src/pages/graphql/schema/catalog-service/queries/products.md, src/pages/graphql/schema/catalog-service/queries/refine-product.md, src/pages/graphql/schema/index.md, src/pages/graphql/schema/live-search/index.md, src/pages/graphql/schema/live-search/queries/attribute-metadata.md, src/pages/graphql/schema/live-search/queries/index.md, src/pages/graphql/schema/live-search/queries/product-search.md, src/pages/graphql/schema/product-recommendations/index.md, src/pages/graphql/schema/product-recommendations/queries/index.md, src/pages/graphql/schema/product-recommendations/queries/recommendations.md, src/pages/graphql/schema/products/queries/categories.md, src/pages/graphql/schema/products/queries/products.md
This pull request (PR) moves the Catalog Service, Live Search, and Recommendatoins queries from the services repo. This essentially reverts #222.
This PR cannot be merged until we get word from the Devsite team that the redirects implemented for [DEVSITE-956](https://jira.corp.adobe.com/browse/DEVSITE-956) have been reversed.
- ...
- ...
=> Move Services queries back to webapi

src/pages/rest/modules/custom-attributes.md
This pull request (PR) fixes a display error caused by not providing a closing backtick around a mutation name.
- ...
- ...
=> Fix highlighting error

src/pages/rest/use-rest/asynchronous-web-endpoints.md, src/pages/rest/use-rest/bulk-endpoints.md, src/pages/rest/use-rest/operation-status-endpoints.md, src/pages/rest/use-rest/operation-status-search.md
This pull request (PR) updates the docs for the asynchronous and bulk REST APIs to include routes for ACCS
- ...
- ...
=> Add routes for ACCS Async/bulk REST APIs

src/pages/graphql/schema/b2b/purchase-order/index.md, src/pages/graphql/schema/b2b/purchase-order/mutations/add-items-to-cart.md, src/pages/rest/modules/import/index.md
In conjunction with https://github.com/AdobeDocs/commerce-extensibility/pull/444, this PR removes spaces from SKUs in example code, since they are causing issues in the integration starter kit.
=> remove spaces from skus

src/pages/graphql/payment-methods/payflow-pro-vault.md
Updated according to the changes in ACP2E-4064
This pull request (PR) adds information according to the changes in ACP2E-4064
- https://developer.adobe.com/commerce/webapi/graphql/payment-methods/payflow-pro-vault/
- ...
=> ACP2E-4064: [Documentation] Update public docs regarding credit cards saved in Vault for PayPal PayFlow Pro for more than 12 months
