AdobeDocs/commerce-webapi

- gatsby-config.js
-  ...
-  ...
-  [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-  [ ] My changes follow the code style of this project.
-  [ ] I have read the **CONTRIBUTING** document.
-  [ ] All new and existing tests passed.
> updating file path

- src/data/navigation/sections/rest.js
- src/pages/index.md
- src/pages/rest/quick-reference/index.md
This pull request (PR) updates links to REST API reference documentation.
- https://developer.adobe.com/commerce/webapi/rest/quick-reference/
- https://developer.adobe.com/commerce/webapi/
> Update REST API links

- package.json
- yarn.lock
Bump aio-theme to 4.6.4 to enable search for newly added commerce-services index.
> Bumped aio-theme

- .github/workflows/test-pull-request.yml
- src/pages/index.md
Test and fix the `test:links` npm script in the PR validation GitHub Actions workflow.
n/a
After bumping `@adobe/gatsby-theme-aio` to 4.6.6 to solve an [error](https://github.com/AdobeDocs/commerce-webapi/actions/runs/3338213014/jobs/5525583363) with installing dependencies with GitHub Actions, our link checking validation started failing with the following error:
```
Internal Error: EACCES: permission denied, open '/home/runner/work/commerce-webapi/commerce-webapi/.yarn/install-state.gz'
Error: EACCES: permission denied, open '/home/runner/work/commerce-webapi/commerce-webapi/.yarn/install-state.gz'
Error: Process completed with exit code 1.
```
This PR is meant to investigate and solve the issue.
I've been unable to reproduce the error locally. It seems to be isolated to GitHub Actions. …
> Test and fix link checking

- src/data/navigation/sections/rest.js
- src/pages/rest/modules/import/index.md
- src/pages/rest/modules/index.md
-  ...
-  https://github.com/magento-commerce/magento2ce/pull/7748
-  [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-  [x] My changes follow the code style of this project.
-  [x] I have read the **CONTRIBUTING** document.
-  [x] All new and existing tests passed.
> ACPT-674: ImportCsvApi Docs

- src/pages/graphql/schema/index.md
This PR adds some text to the GQL schema front page so that it doesn't look like the schema migration failed.
> Add basic text to the GQL schema front page

- src/pages/rest/modules/import/index.md
This pull request (PR) adds an H1 (that's currently missing) to the new [ImportCsv API](https://developer-stage.adobe.com/commerce/webapi/rest/modules/import/) topic that was added for 2.4.6.
> Add H1 to new ImportCsv API topic

- src/pages/_includes/graphql/customer-orders-output.md
- src/pages/graphql/schema/customer/queries/customer.md
This PR ports https://github.com/magento-commerce/devdocs/pull/3082 to the 2.4.6-develop branch of this repo.
> Port Devdocs PR-3082 to Devsite

- src/pages/_includes/graphql/cart-address-input-24.md
This PR ports the changes made in https://github.com/magento-commerce/devdocs/pull/3055 to this repo
> Port Devdocs PR-3055 to Devsite

- src/pages/rest/modules/import/index.md
In  [ACPT-674](https://jira.corp.adobe.com/browse/ACPT-674) , Devdocs was updated with info on new REST endpoint for Import.
Now,  we need to add information about optional gzip compression for the CSV data.
https://jira.corp.adobe.com/browse/ACPT-858
> ACPT-858: Add gzip info to Documentation for Import API

- src/data/navigation/header.js
- src/data/navigation/sections/graphql.js
This PR adds a link from the left nav of the GraphQL Guide to the SpectaQL autogenerated reference.
Staging: https://adobedocs.github.io/commerce-webapi/graphql/
> Add link to GraphQL reference

- src/pages/graphql/schema/orders/mutations/request-return.md
The table is incorrectly formatted it needs a new line, which results in the table being displayed as text
> fix: table display in docs

- spectaql/schema.json
- static/graphql-api/index.html
This PR modifies the 2.4.5 schema to add text to fields and other entities that have no description. This was previously causing rendering problems in the generated output.
Review build: https://adobedocs.github.io/commerce-webapi/graphql/reference/
AC:
* Entire schema renders as expected
* Many instances of "No description available"
> SpectaQL: Add text to null descriptions

- src/pages/graphql/schema/customer/queries/customer.md
This PR removes a duplicate request for `product_sale_price` in the customer orders query
Fixes https://github.com/AdobeDocs/commerce-webapi/issues/93
This change just removes a duplication in a graphql query docs
NAP
> Remove duplicate `product_sale_price` from query

- .github/workflows/index.yml
- package.json
- src/pages/graphql/reference.md
- yarn.lock
The indexing workflow fails with the following error:
```
warning failed to index to Algolia
error Error: EISDIR: illegal operation on a directory, read
at Object.readSync (node:fs:727:3)
at tryReadSync (node:fs:433:20)
at readFileSync (node:fs:479:19)
at getContentFromCache (/home/runner/work/commerce-webapi/commerce-webapi/node_modules/@adobe/gatsby-theme-aio/algolia/helpers/get-content-from-cache.js:29:10)
at getIFrameContent (/home/runner/work/commerce-webapi/commerce-webapi/node_modules/@adobe/gatsby-theme-aio/algolia/helpers/get-iframe-content.js:34:7)
at transformer (/home/runner/work/commerce-webapi/commerce-webapi/node_modules/@adobe/gatsby-theme-aio/algolia/index-records.js:84:20)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at getObjectsMapByQuery …
```
> Fix indexing

- src/pages/graphql/develop/index.md
> Fix spelling

- src/pages/rest/tutorials/orders/order-create-customer.md
> fixing a typo

- src/pages/graphql/schema/products/interfaces/routable.md
This pull request (PR) fixes linting errors that somehow made it through a previous merge.
- ...
- ...
> Fix linting errors

- src/data/navigation/sections/graphql.js
This pull request (PR) fixes a merge error I introduced when fixing a merge conflict to the `2.4.7-develop` branch in #121 
- ...
- ...
> Fix merge error

- src/pages/_includes/graphql/customer-address-input-24.md
- src/pages/_includes/graphql/customer-address-output-24.md
- src/pages/_includes/graphql/customer-output-24.md
- src/pages/_includes/graphql/notes/beta-example.md
- src/pages/_includes/graphql/notes/beta.md
- src/pages/get-started/api-security.md
- src/pages/graphql/schema/attributes/queries/attributes-form.md
- src/pages/graphql/schema/attributes/queries/attributes-list.md
- src/pages/graphql/schema/attributes/queries/custom-attribute-metadata-v2.md
- src/pages/graphql/schema/customer/mutations/create-address.md
- src/pages/graphql/schema/customer/mutations/create-v2.md
- src/pages/graphql/schema/customer/mutations/update-address.md
- src/pages/graphql/schema/customer/mutations/update-v2.md
- src/pages/graphql/schema/customer/queries/customer.md
- src/pages/graphql/schema/products/interfaces/routable.md
- src/pages/graphql/usage/caching.md
This pull request (PR) adds notes about functionality available in 2.4.7-beta1 only. 
To identify the changes that need notes, I reviewed the changed files in the sync PR (#121).
- see changed files
https://developer-stage.adobe.com/commerce/webapi/
> COMDOX-660: Added notes for 2.4.7-beta1 updates

- src/pages/_includes/graphql/customer-address-output-24.md
- src/pages/_includes/graphql/customer-output-24.md
- src/pages/graphql/schema/customer/queries/customer.md
This pull request (PR) reverts a PR (#147) that was merged prematurely. It is for 2.4.7-beta2.
> Revert "Merge pull request #147 from loginesta/LYNX-162"

- src/data/navigation/sections/graphql.js
This pull request (PR) duplicates #172 , but it's for the `2.4.7-develop` branch.
- ...
- ...
> Nav fix for 247

- src/data/navigation/sections/graphql.js
This pull request (PR) add the `recommendations` query to the TOC.
> Add recommendations query to TOC

- src/pages/graphql/usage/index.md
This pull request (PR) adds a statement about UTC values.
- ...
- ...
> Add timestamps statement

- src/pages/graphql/schema/customer/queries/is-email-available.md
This pull request (PR) updates is-email-available.md, the line break was missing between lines once the page was published
- https://developer.adobe.com/commerce/webapi/graphql/schema/customer/queries/is-email-available/
- ...
> Update is-email-available.md, the line break was missing between lines once the page has been published

- src/_includes/graphql/customer-orders-output.md
This pull request (PR) fix typo error.
- https://developer.adobe.com/commerce/webapi/graphql/schema/customer/queries/customer/
- N/A
> Fix typo error

- src/data/navigation/sections/rest.js
- src/pages/rest/index.md
- src/pages/rest/quick-reference/index.md
This pull request (PR) improves the description metadata for the REST API reference topics and adds some minor editorial revisions to the REST overview.
- https://developer.adobe.com/commerce/webapi/rest/
- https://developer.adobe.com/commerce/webapi/rest/quick-reference/
> Update REST API metadata

- src/pages/graphql/payment-methods/index.md
- src/pages/graphql/payment-services/index.md
- src/pages/graphql/schema/checkout/mutations/create-payment-order.md
- src/pages/graphql/schema/checkout/mutations/index.md
- src/pages/graphql/schema/checkout/mutations/sync-payment-order.md
- src/pages/graphql/schema/checkout/queries/get-payment-config.md
- src/pages/graphql/schema/checkout/queries/get-payment-order.md
- src/pages/graphql/schema/checkout/queries/get-payment-sdk.md
- src/pages/graphql/schema/checkout/queries/index.md
This pull request (PR) adds basic info and links to the Payment Services extension.
- ...
- ...
> Miscellaneous cleanup

- src/pages/graphql/payment-methods/index.md
- src/pages/graphql/payment-services/checkout.md
This pull request (PR) updates links to new mutations and queries
- ...
- ...
> Updates links in the checkout

- src/pages/graphql/payment-methods/braintree-vault.md
- src/pages/graphql/payment-methods/braintree.md
- src/pages/graphql/schema/cart/mutations/set-payment-place-order.md
- src/pages/graphql/schema/checkout/mutations/create-braintree-client-token.md
- src/pages/graphql/schema/checkout/queries/agreements.md
This pull request (PR) updates links to Something Digital, which was subsequently acquired by a company named Rightpoint.
- ...
- ...
> Update references to Something Digital

- src/pages/rest/tutorials/bundle-product/create-bundle-product.md
This pull request (PR) fixes #274. 
- https://developer.adobe.com/commerce/webapi/rest/tutorials/bundle-product/create-bundle-product/
> GH-274: Fix typo

- src/pages/graphql/schema/cart/mutations/apply-coupons.md
- src/pages/graphql/schema/cart/mutations/remove-coupons.md
- src/pages/rest/modules/multicoupon/index.md
This pull request (PR) documents all new features added by multicoupon modules
- ...
> LYNX-220: Added multicoupon documentation

- src/pages/graphql/schema/cart/mutations/clear-cart.md
- src/pages/graphql/schema/cart/mutations/index.md
This pull request (PR) add information about the new `ClearCart` mutation. This is part of `2.4.7-beta3`
-
> LYNX-327: Added ClearCart mutation

- src/pages/graphql/schema/cart/mutations/estimate-totals.md
- src/pages/graphql/schema/cart/mutations/index.md
This PR provides documentation for `estimateTotals` mutation.
See https://jira.corp.adobe.com/browse/LYNX-335 for details.
Implementation ticket for the mutation: https://jira.corp.adobe.com/browse/LYNX-312
- src/pages/graphql/schema/cart/mutations/estimate-totals.md
- src/pages/graphql/schema/cart/mutations/index.md
> LYNX-335: estimateTotals mutation documentation

- src/data/navigation/sections/graphql.js
This pull request (PR) adds navigation for the topic added in #303 
- ...
- ...
> Add navigation for new topic

- spectaql/schema.json
This placeholder schema is for checking links for `2.4.7`
> Placeholder schema

- src/pages/graphql/schema/cart/mutations/clear-cart.md
This pull request (PR) adds the edition for the `clearCart` mutation.
- ...
- ...
> clearCart is Commerce-only

- src/pages/rest/modules/multicoupon/index.md
This pull request (PR) adds context about the multicoupon REST endpoints. I also edited somethings I missed in the review of #296 
- ...
- ...
> Updates to multicoupon

- src/pages/rest/modules/import/index.md
This pull request (PR) adds info about UTF-8 encoding. The info is being added as a result of an internal request.
- ...
- ...
> Add UTF-8 info

- src/pages/get-started/gs-web-api-request.md
- src/pages/graphql/payment-methods/klarna.md
- src/pages/index.md
This pull request (PR) applies some minor editorial fixes to the home page.
- https://developer.adobe.com/commerce/webapi/
> Editorial fixes for the home page 

- src/pages/graphql/schema/customer/mutations/generate-token.md
This pull request (PR) update the documentation for: [LYNX-391](https://jira.corp.adobe.com/browse/LYNX-391)
- https://developer.adobe.com/commerce/webapi/graphql/schema/customer/mutations/generate-token/
- ...
> LYNX-391: add new generateToken error message

- .github/workflows/github-pages.yml
- .github/workflows/index.yml
- .github/workflows/publish.yml
- .github/workflows/stage.yml
- .github/workflows/test-pull-request.yml
This pull request (PR) updates the PR testing GH workflow to split the testing jobs into three for better control and maintenance. Also, it removes code duplication using a composed action (https://github.com/commerce-docs/devsite-install-action) in all relevant workflows and removes unnecessary permissions in the testing PR workflow and the Pages workflow. Further restriction updates will be done later in separate PRs.
https://github.com/AdobeDocs/commerce-testing/pull/114
> Refactor GitHub workflows

- src/pages/graphql/develop/functional-testing.md
This pull request updates GraphQL functional testing instruction regarding creating and using fixtures. The information currently present on the page is outdated as it describes deprecated process. 
See https://github.com/magento-commerce/quality-guild/issues/81 for details.
- https://developer.adobe.com/commerce/webapi/graphql/develop/functional-testing
> Review and update WepApi functional documentation

- src/pages/graphql/develop/resolvers.md
This pull request (PR) updates the copyright in code samples.
- https://developer.adobe.com/commerce/webapi/graphql/develop/resolvers/
> Update the copyright in code samples

- src/data/navigation/sections/graphql.js
- src/pages/graphql/payment-methods/index.md
- src/pages/graphql/payment-services-extension/index.md
- src/pages/graphql/payment-services-extension/mutations/index.md
- src/pages/graphql/payment-services-extension/queries/index.md
- src/pages/graphql/payment-services-extension/workflows/index.md
This pull request (PR) adds index files for the updated folder for Payment Services in GraphQL.
- ...
- ...
[PAY-5702](https://jira.corp.adobe.com/browse/PAY-5702)
> Adds index files to the new Payment Services Extension folder and subfolders in GraphQL docs

- src/pages/get-started/api-security.md
This pull request (PR) makes some minor updates to metadata.
> docs: minor copy edit

- src/pages/graphql/schema/customer/queries/is-email-available.md
This pull request (PR) fixes [BICs](https://developer.adobe.com/commerce/php/development/backward-incompatible-changes/) link after file structure changes.
- https://developer.adobe.com/commerce/webapi/graphql/schema/customer/queries/is-email-available/
> Fix BIC link

- src/pages/get-started/authentication/gs-authentication-token.md
This pull request (PR) updates IMS docs per SME feedback.
Related PR: https://github.com/AdobeDocs/commerce-php/pull/242
- https://developer.adobe.com/commerce/webapi/get-started/authentication/gs-authentication-token/
> Update IMS docs

- src/pages/graphql/usage/caching.md
This pull request (PR) removes a duplicate note 
- src/pages/graphql/usage/caching.md
- ...
> Remove duplicated note

- src/_includes/custom-attribute-installation.md
- src/_includes/graphql/custom-attribute-availability.md
- src/data/navigation/sections/graphql.js
- src/data/navigation/sections/rest.js
- src/pages/graphql/schema/attributes/index.md
- src/pages/graphql/schema/attributes/mutations/index.md
- src/pages/graphql/schema/attributes/mutations/set-custom-cart-item.md
- src/pages/graphql/schema/attributes/mutations/set-custom-cart.md
- src/pages/graphql/schema/attributes/mutations/set-custom-company.md
- src/pages/graphql/schema/attributes/mutations/set-custom-credit-memo-item.md
- src/pages/graphql/schema/attributes/mutations/set-custom-credit-memo.md
- src/pages/graphql/schema/attributes/mutations/set-custom-invoice-item.md
- src/pages/graphql/schema/attributes/mutations/set-custom-invoice.md
- src/pages/graphql/schema/attributes/mutations/set-custom-negotiable-quote.md
- src/pages/rest/modules/custom-attributes.md
- src/pages/rest/modules/index.md
This pull request (PR) adds mutations that were originally created for ACCS and OOPE app, but can now be implemented on in-process environments. The B2B functionality is available in ACCS but has not been released in PaaS.
- ...
- ...
> Add mutations for custom attributes

- src/pages/rest/modules/custom-attributes.md
- This PR changes the target of a link that was previously going nowhere.
- ...
> Update link to heading

- src/data/navigation/sections/rest.js
- src/pages/rest/authentication/index.md
- src/pages/rest/authentication/server-to-server.md
- src/pages/rest/authentication/user.md
> Update  authentication section to clarify OAuth Authorization  flows

- package.json
- yarn.lock
This pull request (PR) upgrades spectaql to the latest release to prepare it for customization #479.
To learn about changes, refer to https://github.com/anvilco/spectaql/blob/main/CHANGELOG.md.
- https://developer.adobe.com/commerce/webapi/reference/graphql/saas/
- https://developer.adobe.com/commerce/webapi/reference/graphql/2.4.8/
- https://commerce-docs.github.io/commerce-webapi/reference/graphql/saas/
- https://commerce-docs.github.io/commerce-webapi/reference/graphql/2.4.8/
> Upgrade spectaql

- src/pages/graphql/payment-methods/payflow-pro-vault.md
Reverts AdobeDocs/commerce-webapi#487
> Revert "Update payflow-pro-vault.md"
